# This is the file meant for server config, and it has the network config for TCP Server.
# This file makes environment changes and flexible deployment easy without recompilation.

#used the 0.0.0.0 Server IP Addr so that it can listen on all network interfaces.
server.ip=0.0.0.0
# server port numb
server.port=3000
